services:
  system-db:
    image: docker.io/postgres:17-alpine3.21
    container_name: system-db
    environment:
      POSTGRES_USER: crh_user
      POSTGRES_PASSWORD: crh_password
      POSTGRES_DB: system-db
      TZ: Asia/Bangkok
    ports:
      - 5432:5432
    volumes:
      - ./system-db:/var/lib/postgresql/data

