server:
    port: 8443
    ssl:
        key-store: classpath:ssl/app_keystore.p12
        key-store-password: ${KEYSTORE_PASSWORD}
        key-store-type: PKCS12
        key-alias: ssl
        key-password: ${KEYSTORE_PASSWORD}
        enabled-protocols: TLSv1.2, TLSv1.3
        cipher-suites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_RSA_WITH_AES_128_GCM_SHA256

spring:
    security:
        oauth2:
            provider:
                issuer-uri: https://xxx/realms/xxx
                jwk-set-uri: https://xxx/realms/xxx/protocol/openid-connect/certs
                audience: xxx
                client-id: xxxxx
                admin-realm: xxxxx
                admin-client-id: xxxxx
                admin-client-secret: xxxxxxxxxxxxx
                admin-username: xxxxx
                admin-password: xxxxx
                auth-uri: https://xxx
    flyway:
        enabled: true
    datasource:
        db-su-manager:
            jdbc-url: jdbc:postgresql://localhost:5432/system-db
            r2dbc-url: r2dbc:postgresql://localhost:5432/system-db 
            username: crh_user
            password: crh_password
            locations: classpath:migration/DbSuManager
            driver-class-name: org.postgresql.Driver
logging:
    level:
        root: INFO
        org.flywaydb: DEBUG